2024-09-28 18:26:06,700 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 6167c0f2009e4f93d745bf1859bc5e8e).
2024-09-28 18:45:55,479 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 20:20:50,136 - root - INFO - Commande: mute, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 20:20:54,006 - discord.app_commands.tree - ERROR - Ignoring exception in command 'mute'
Traceback (most recent call last):
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\mute.py", line 44, in mute
    await interaction.response.send_message(f"{user.mention} a été mute pour la raison : {reason}.", ephemeral=False)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\mute.py", line 48, in mute
    await interaction.response.send_message(f"Une erreur est survenue : {str(e)}", ephemeral=True)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mute' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-09-28 20:21:31,699 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:05:42,153 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 1702b35a7d4ed52b389c1d8b1f6f662b).
2024-09-28 21:05:55,674 - root - INFO - Commande: mute, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:06:16,039 - root - INFO - Commande: unmute, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:06:34,156 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:07:36,744 - root - INFO - Commande: say, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:08:12,833 - root - INFO - Commande: ping, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:08:20,707 - root - INFO - Commande: say, Utilisateur: dawndlb, Serveur: TsunaLab
2024-09-28 21:08:38,538 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:29:17,087 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:29:20,887 - discord.app_commands.tree - ERROR - Ignoring exception in command 'clear'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\clear.py", line 31, in clear
    await interaction.response.send_message(f"J'ai supprimé {len(deleted) - 1} messages.", ephemeral=False)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clear' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-09-28 21:30:02,048 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:30:07,399 - discord.app_commands.tree - ERROR - Ignoring exception in command 'clear'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\clear.py", line 31, in clear
    await interaction.response.send_message(f"J'ai supprimé {len(deleted) - 1} messages.", ephemeral=False)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clear' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-09-28 21:37:17,409 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 7f413a8f0a134eee1c898662988e785b).
2024-09-28 21:37:30,588 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:37:34,070 - discord.app_commands.tree - ERROR - Ignoring exception in command 'clear'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\clear.py", line 33, in clear
    await interaction.channel.send(f"J'ai supprimé {len(deleted)} messages.", ephemeral=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Messageable.send() got an unexpected keyword argument 'ephemeral'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 872, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clear' raised an exception: TypeError: Messageable.send() got an unexpected keyword argument 'ephemeral'
2024-09-28 21:38:42,680 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 20e5321d1ccba564e32556a834bbdfa7).
2024-09-28 21:38:55,419 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:40:27,207 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: ce953e90921b9c84ef66bbe6a4ca761a).
2024-09-28 21:40:43,119 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:42:27,969 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: f951531198ba47313d59ff46f07cbf34).
2024-09-28 21:43:00,373 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:43:49,456 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: df9c912c685faf4dd8f3af0bb34998db).
2024-09-28 21:44:05,049 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:44:08,802 - discord.app_commands.tree - ERROR - Ignoring exception in command 'clear'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\clear.py", line 34, in clear
    await interaction.channel.send(f"J'ai supprimé {len(deleted - 1)} messages.")
                                                      ~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'list' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 872, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clear' raised an exception: TypeError: unsupported operand type(s) for -: 'list' and 'int'
2024-09-28 21:44:36,173 - root - INFO - Commande: clear, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:44:41,629 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284466014490198076 responded with 429. Retrying in 0.50 seconds.
2024-09-28 21:44:42,599 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284466013676765249 responded with 429. Retrying in 0.53 seconds.
2024-09-28 21:44:43,534 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465716900270111 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:44:44,551 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465715822465034 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:44:45,564 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465541431427103 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:44:46,608 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465540022403103 responded with 429. Retrying in 0.52 seconds.
2024-09-28 21:44:47,568 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465282521366529 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:44:48,574 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465281993015388 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:44:49,587 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465261520617567 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:44:50,719 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465260690014269 responded with 429. Retrying in 0.41 seconds.
2024-09-28 21:44:51,638 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465229714952204 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:44:52,601 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465228645535859 responded with 429. Retrying in 0.53 seconds.
2024-09-28 21:44:53,531 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465145405374607 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:44:54,623 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284465144788811908 responded with 429. Retrying in 0.52 seconds.
2024-09-28 21:44:55,572 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464775904104450 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:44:56,579 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464721512370176 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:44:57,585 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464720727900244 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:44:58,566 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464694890860605 responded with 429. Retrying in 0.57 seconds.
2024-09-28 21:44:59,604 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464693624176721 responded with 429. Retrying in 0.53 seconds.
2024-09-28 21:45:00,639 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464520739291146 responded with 429. Retrying in 0.50 seconds.
2024-09-28 21:45:01,591 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464520000962642 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:45:02,563 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464479408623629 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:45:03,562 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464478661902387 responded with 429. Retrying in 0.57 seconds.
2024-09-28 21:45:04,593 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464444562214913 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:45:05,547 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464442905726977 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:45:06,670 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464276488196199 responded with 429. Retrying in 0.47 seconds.
2024-09-28 21:45:07,587 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464275271843903 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:45:08,610 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464229348413470 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:45:09,523 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464228291317802 responded with 429. Retrying in 0.61 seconds.
2024-09-28 21:45:10,553 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464073366306827 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:45:11,507 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284464072355610706 responded with 429. Retrying in 0.62 seconds.
2024-09-28 21:45:12,603 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284462176945307658 responded with 429. Retrying in 0.53 seconds.
2024-09-28 21:45:45,866 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: TsunaLab
2024-09-28 21:47:13,799 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284462096431452160 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:47:14,794 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461617563566140 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:47:15,862 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461616779497493 responded with 429. Retrying in 0.52 seconds.
2024-09-28 21:47:16,791 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461568431493194 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:47:17,830 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461567550951526 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:47:18,798 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461534780719145 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:47:19,826 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461533711306753 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:47:20,907 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461472575131668 responded with 429. Retrying in 0.47 seconds.
2024-09-28 21:47:21,847 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461402995822602 responded with 429. Retrying in 0.53 seconds.
2024-09-28 21:47:22,803 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461040570073231 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:47:23,818 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461039701725234 responded with 429. Retrying in 0.57 seconds.
2024-09-28 21:47:24,773 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461027257487491 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:47:25,766 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461025822773270 responded with 429. Retrying in 0.62 seconds.
2024-09-28 21:47:26,919 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461006768046133 responded with 429. Retrying in 0.50 seconds.
2024-09-28 21:47:27,841 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284461006185300090 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:47:28,791 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460947909640235 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:47:29,769 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460947129368729 responded with 429. Retrying in 0.61 seconds.
2024-09-28 21:47:30,838 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460937281142814 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:47:31,785 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460936513458227 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:47:32,831 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460903193907201 responded with 429. Retrying in 0.55 seconds.
2024-09-28 21:47:33,796 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460902753632276 responded with 429. Retrying in 0.58 seconds.
2024-09-28 21:47:34,792 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460854514810901 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:47:35,771 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460853801914380 responded with 429. Retrying in 0.61 seconds.
2024-09-28 21:47:36,822 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460853235683338 responded with 429. Retrying in 0.56 seconds.
2024-09-28 21:47:37,794 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460853009055776 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:47:38,811 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460830473195560 responded with 429. Retrying in 0.57 seconds.
2024-09-28 21:47:39,761 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460829592522852 responded with 429. Retrying in 0.62 seconds.
2024-09-28 21:47:40,923 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460771685961893 responded with 429. Retrying in 0.46 seconds.
2024-09-28 21:47:41,756 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460770788380799 responded with 429. Retrying in 0.63 seconds.
2024-09-28 21:47:42,764 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460752987754507 responded with 429. Retrying in 0.61 seconds.
2024-09-28 21:47:43,760 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460752140238898 responded with 429. Retrying in 0.62 seconds.
2024-09-28 21:47:44,786 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460715620433933 responded with 429. Retrying in 0.60 seconds.
2024-09-28 21:49:46,201 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460548964220929 responded with 429. Retrying in 0.48 seconds.
2024-09-28 21:49:47,064 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460547684827178 responded with 429. Retrying in 0.62 seconds.
2024-09-28 21:49:48,111 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460479481253984 responded with 429. Retrying in 0.57 seconds.
2024-09-28 21:49:49,129 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460191470981121 responded with 429. Retrying in 0.54 seconds.
2024-09-28 21:49:50,084 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460190401302528 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:49:51,187 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460174547091529 responded with 429. Retrying in 0.50 seconds.
2024-09-28 21:49:52,288 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460174022541322 responded with 429. Retrying in 0.39 seconds.
2024-09-28 21:49:53,089 - discord.http - WARNING - We are being rate limited. DELETE https://discord.com/api/v10/channels/1280156395831951460/messages/1284460141445386301 responded with 429. Retrying in 0.59 seconds.
2024-09-28 21:49:53,923 - discord.app_commands.tree - ERROR - Ignoring exception in command 'clear'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\moderation\clear.py", line 34, in clear
    await interaction.channel.send(f"J'ai supprimé {len(deleted - 1)} messages.")
                                                      ~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'list' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 872, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clear' raised an exception: TypeError: unsupported operand type(s) for -: 'list' and 'int'
2024-09-28 22:21:06,894 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 0c1fb874115c6ca99e7195c421be6051).
2024-09-28 22:23:51,187 - root - INFO - Commande: pp, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-28 22:24:07,645 - root - INFO - Commande: pp, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-28 22:24:24,365 - root - INFO - Commande: pp, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-28 22:27:16,400 - root - INFO - Commande: pp, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-28 23:28:43,788 - root - INFO - Commande: pp, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-28 23:55:19,701 - discord.gateway - INFO - Shard ID None has successfully RESUMED session 0c1fb874115c6ca99e7195c421be6051.
2024-09-28 23:57:03,058 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-29 00:25:17,498 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: b45b687b1e8f763dd450f96f679e4c17).
2024-09-29 00:25:56,156 - root - INFO - Commande: joke, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-29 00:26:20,870 - root - INFO - Commande: fact, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-29 00:26:37,321 - root - INFO - Commande: quote, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-29 00:26:38,312 - discord.app_commands.tree - ERROR - Ignoring exception in command 'quote'
Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 1068, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1126, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1159, in _create_connection_transport
    await waiter
  File "C:\Users\tsuna\AppData\Local\Programs\Python\Python312\Lib\asyncio\sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\tsuna\AppData\Local\Programs\Python\Python312\Lib\asyncio\sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\tsuna\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tsuna\Desktop\Soushi\modules\basic\roll.py", line 16, in quote
    async with session.get("https://api.quotable.io/random") as response:
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\client.py", line 659, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 557, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 1002, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 1336, in _create_direct_connection
    raise last_exc
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 1305, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\aiohttp\connector.py", line 1070, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.quotable.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsuna\Desktop\Soushi\.env\Lib\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'quote' raised an exception: ClientConnectorCertificateError: Cannot connect to host api.quotable.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')]
2024-09-29 00:27:50,075 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 328a0ef2941a8e8eeb0529c6c8bc7eb2).
2024-09-29 00:29:02,590 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 405a5d853d2bd55589f0dd7d30fdcb20).
2024-09-29 00:29:30,112 - root - INFO - Commande: quote, Utilisateur: tawonto, Serveur: Le Cabanon
2024-09-29 00:31:25,816 - root - INFO - Commande: logs, Utilisateur: tawonto, Serveur: Le Cabanon
